# Generated by Django 3.1.6 on 2021-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('users', '0004_auto_20210513_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.ManyToManyField(help_text="The user's Stripe Subscription object, if it exists", to='djstripe.Subscription'),
        ),
    ]
