# Generated by Django 3.1.6 on 2021-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '__first__'),
        ('users', '0007_customuser_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.ManyToManyField(help_text="The user's Stripe Subscription object, if it exists", related_name='subscription', to='subscriptions.CustomSubscription'),
        ),
    ]
