# Generated by Django 3.1.6 on 2021-06-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210603_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tracking_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
