from django.urls import path

from . import views

urlpatterns = [
    path(
        "email/open/<slug:id>",
        views.TrackEmailOpen.as_view(),
        name="track_email_open",
    ),
    path(
        "email/click/<slug:id>",
        views.TrackEmailClick.as_view(),
        name="track_email_click",
    ),
    path(
        "start/",
        views.CreateCampaignStartView.as_view(),
        name="create_campaign_start",
    ),
    path(
        "recipients/",
        views.CreateCampaignRecipientsView.as_view(),
        name="create_campaign_recipients",
    ),
    path(
        "message/",
        views.CreateCampaignMessageView.as_view(),
        name="create_campaign_message",
    ),
    path(
        "personalize/<int:pk>/",
        views.CampaignGetAllEmailsPreview.as_view(),
        name="CampaignGetAllEmailsPreview",
    ),
    path(
        "options/",
        views.CreateCampaignOptionView.as_view(),
        name="create_campaign_options",
    ),
    path("view/", views.CampaignView.as_view(), name="campaign_view"),
    path(
        "savecamp/<int:pk>/",
        views.CreateCampaignSendView.as_view(),
        name="create_campaign_send",
    ),
    path(
        "overview/<int:pk>/",
        views.GetCampaignOverview.as_view(),
        name="Get_campaign_overview",
    ),
    path(
        "recipients/people/<int:pk>/",
        views.AllRecipientView.as_view(),
        name="recipients",
    ),
    path(
        "recipients/<int:pk>/",
        views.RecipientDetailView.as_view(),
        name="recipients_update",
    ),
    path(
        "settings-leadcatcher/",
        views.CampaignleadCatcher.as_view(),
        name="settings-leadcatcher",
    ),
    path(
        "settings-leadcatcherView/<int:pk>/",
        views.LeadCatcherView.as_view(),
        name="LeadCatcherView",
    ),
    path(
        "update-leadcatcherstatus/",
        views.LeadCatcherStatusUpdateView.as_view(),
        name="update-leadcatcherstatus",
    ),
    path(
        "settings-leadcatcher/<int:pk>/",
        views.LeadCatcherUpdateView.as_view(),
        name="campaignleadcatcher",
    ),
    path(
        "sequence/<int:pk>/",
        views.CampaignMessages.as_view(),
        name="campaignmessage",
    ),
    path("prospects/", views.ProspectsView.as_view(), name="procpects"),
    path(
        "prospects/count",
        views.ProspectsCountView.as_view(),
        name="procpects_count",
    ),
    path(
        "prospects/detail/",
        views.ProspectsDetailView.as_view(),
        name="procpects_detail",
    ),
    path(
        "recipientunsubcribe/",
        views.RecipientUnsubcribe.as_view(),
        name="recipient_unsubcribe",
    ),
    path(
        "recipientunassigned/",
        views.RecipientUnassignedView.as_view(),
        name="recipientunassigned",
    ),
    path(
        "create/", views.CampaignCreateView.as_view(), name="create_campaign"
    ),
    path(
        "delete/<int:pk>/",
        views.CampaignDeleteView.as_view(),
        name="delete_campaign",
    ),
    path(
        "sequence-update/",
        views.CampaignSequenceUpdateView.as_view(),
        name="sequence-update",
    ),
    path("list/", views.CampaignListView.as_view(), name="list_campaign"),
    path(
        "leads/list-campaigns/",
        views.CampaignWithLeadsListView.as_view(),
        name="list_campaign",
    ),
    path(
        "overview-summary/<int:pk>/",
        views.CampaignOverviewSummary.as_view(),
        name="Get_campaign_overview_summary",
    ),
    path(
        "email-stats/<slug:option>/<int:email_id>/",
        views.EmailStatsView.as_view(),
        name="get-email-stats",
    ),
    path(
        "campaign-stats/<slug:option>/<int:campaign_id>/",
        views.CampaignStatsView.as_view(),
        name="get-campaign-stats",
    ),
    path(
        "details-sequence/<int:pk>/",
        views.CampaignDetailsSequenceView.as_view(),
        name="details-sequence",
    ),
    path(
        "details-recipients/<int:pk>/",
        views.CampaignDetailsRecipientsView.as_view(),
        name="details-recipients",
    ),
    path(
        "details-recipients-add/<int:pk>",
        views.CampaignDetailsRecipientsAddView.as_view(),
        name="details-recipients-add",
    ),
    path(
        "details-recipients-update-status/<int:pk>/",
        views.CampaignDetailsRecipientsUpdateStatusView.as_view(),
        name="details-recipients-update",
    ),
    path(
        "details-recipients-delete/<int:pk>/",
        views.CampaignDetailsRecipientsDeleteView.as_view(),
        name="details-recipients-update",
    ),
    path(
        "details-settings/<int:pk>/",
        views.CampaignDetailsSettingsView.as_view(),
        name="details-settings",
    ),
    path(
        "details-settings-update/<int:pk>/",
        views.CampaignDetailsSettingsUpdateView.as_view(),
        name="details-settings-update",
    ),
    path("schedule/", views.CampaignScheduleView.as_view(), name="schedule"),
    path("leads/", views.CampaignLeadsView.as_view(), name="leads"),
    path(
        "settings-lead/<int:campaign_id>/",
        views.CampaignLeadSettingView.as_view(),
        name="lead-settings",
    ),
    path(
        "lead-detail/<int:camp_id>/<int:lead_id>/",
        views.LeadDetailView.as_view(),
        name="lead-detail",
    ),
    path(
        "recipient/<int:camp_id>/<int:lead_id>/",
        views.RecipientSequenceView.as_view(),
        name="lead-detail",
    ),
    path(
        "lead/status/<int:lead_id>/",
        views.LeadStatusUpdate.as_view(),
        name="lead-update-status",
    ),
    path(
        "lead/reply/<int:camp_id>/<int:lead_id>/",
        views.LeadReply.as_view(),
        name="lead-reply",
    ),
    path(
        "update-status/<int:pk>",
        views.CampaignUpdateStatus.as_view(),
        name="campaign_update_status",
    ),
    path(
        "check-recipients",
        views.RecipientsCheck.as_view(),
        name="campaign_check-recipients",
    ),
    path(
        "audience/tags/",
        views.AudienceTagListView.as_view(),
        name="audience-tags",
    ),
    path(
        "audience/tags/<int:pk>",
        views.AudienceTagDeleteView.as_view(),
        name="audience-tags",
    ),
    path(
        "audience/create/",
        views.AudienceCreateView.as_view(),
        name="create_audience",
    ),
    path(
        "audience/list/",
        views.AudienceListView.as_view(),
        name="audience_list",
    ),
]
